# Uncomment this line to define a global platform for your project
platform :ios, "6.0"

target "accessibility" do
pod 'Google-Maps-iOS-SDK'
pod 'AFNetworking'
pod 'Base64'
pod 'MBProgressHUD'
end

target "accessibilityTests" do

end

